ALTER TABLE paciente
ADD COLUMN logradouro VARCHAR(100) NOT NULL,
ADD COLUMN bairro VARCHAR(100) NOT NULL,
ADD COLUMN cep VARCHAR(9) NOT NULL,
ADD COLUMN complemento VARCHAR(100),
ADD COLUMN numero VARCHAR(20),
ADD COLUMN uf CHAR(2) NOT NULL,
ADD COLUMN cidade VARCHAR(100) NOT NULL;
